	</main>

	<footer class="footerBlock">
	    <article class="mainBG callBox">
	        <div class="maxW flex-row-wrap-center-line">
	            <span>需要協助嗎?</span>
	            <a href="mailto:service@net-chinese.com.tw"><i class="far fa-envelope"></i>service@net-chinese.com.tw</a>
	        </div>
	    </article>
	    <article class="bg infoBlock">
	        <div class="maxW">
	            <ul id="footerInfo" class="flex-row-nowrap-stretch footerInfoList">
	                <li class="">
	                    <a class="" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">關於</a>
	                    <ul id="collapseOne" class="footerInfoSubList collapse" aria-labelledby="headingOne" data-parent="#footerInfo">
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/MenuLink/Index/129">關於我們</a></li>
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/MenuLink/Index/130">改版宣言</a></li>
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/MenuLink/Index/131">改版歷程</a></li>
	                        <li class="fbIcon">
	                            <a href="https://www.facebook.com/NetChineseFans">
	                                <i class="fab fa-facebook"></i>
	                            </a>
	                        </li>
	                    </ul>
	                </li>
	                <li class="">
	                    <a class="" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">條款資訊</a>
	                    <ul id="collapseTwo" class="footerInfoSubList collapse" aria-labelledby="headingOne" data-parent="#footerInfo">
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments/index/MTS">會員服務條款</a></li>
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments/index/PP">隱私權政策</a></li>
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments/index/DNPT">域名申購條款</a></li>
	                                                <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments/index/PDPP">個資保護政策</a></li>                        
	                                                <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments">資訊安全政策</a></li>                        
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/OtherDocuments/index/AAP">反濫用政策</a></li>    
	                    </ul>
	                </li>
	                <li class="">
	                    <a class="" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">客戶支援</a>
	                    <ul id="collapseThree" class="footerInfoSubList collapse" aria-labelledby="headingOne" data-parent="#footerInfo">
	                        <li><a href="mailto:service@net-chinese.com.tw?Subject=舉報違規">我要舉報違規</a></li>
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/MenuLink/Index/119">表單下載</a></li><!-------------------------待改------------------------------->
	                        <li><a href="https://www.net-chinese.com.tw/nc/index.php/WhoisSearchEdit">Whois查詢</a></li>
	                    </ul>
	                </li>
	                <li class="">
	                    <a class="" href="#" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">聯絡我們</a>
	                    <ul id="collapseFour" class="footerInfoSubList collapse" aria-labelledby="headingOne" data-parent="#footerInfo">
	                        <li>
	                            <a href="tel:0225319696"><i class="fas fa-phone"></i>(02)2531-9696</a>
	                        </li>
	                        <li>
	                            <i class="fas fa-fax" style="margin-right: 5px; color: #b0b0b0;"></i>(02)2531-9522
	                        </li>
	                        <li>
	                            <a href="mailto:service@net-chinese.com.tw"><i class="far fa-envelope"></i>service@net-chinese.com.tw</a>
	                        </li>
	                        <li>
	                            <a href="skype:net-chinese?call"><i class="fab fa-skype"></i>net-chinese</a>
	                        </li>
	                        <li class="serverBox">
	                            服務時間：<br>(週一至週五 上午8:00-晚上8:00)                        </li>
	                    </ul>
	                </li>
	            </ul>
	        </div>
	    </article>
	    <article class="bg2 imgBlock">
	        <div class="maxW">
	            <ul class="flex-row-nowrap-center-center">
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/icann.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/iso29100.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/clearinghouse.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/taipei.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/XN.jpg" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/iso9001.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/iso27001.png" alt=""></li>
	                <li><img src="https://www.net-chinese.com.tw/nc/images/more/cnnic.jpg" alt=""></li>
	                <li><a href="http://www.netc.tw/dotgov/index.html"><img src="https://www.net-chinese.com.tw/nc/images/more/twnic.png" alt=""></a></li>
	            </ul>
	        </div>
	    </article>
	    <article class="CopyrightBox">
	        <div class="maxW">
	            <p>此網站由網路中文資訊股份有限公司擁有並進行營運<br>網路中文資訊股份有限公司版權所有 © Copyright 2018 Net-Chinese Co., Ltd. All Rights Reserved.</p>
	        </div>
	    </article>
	</footer>

