    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- 網頁圖示 -->
    <link rel="shortcut icon" href="https://www.net-chinese.com.tw/nc/favicon.ico?123">
    <!-- /End -->
    <link rel="stylesheet" type="text/css" href="https://www.net-chinese.com.tw/nc/vendor/bootstrap4-datetimepicker/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="https://www.net-chinese.com.tw/nc/css/AlertConfirm.css">
    <link rel="stylesheet" type="text/css" href="https://www.net-chinese.com.tw/nc/css/sort.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link href="default.css" rel="stylesheet" type="text/css">
	
    <title>網路中文 : 全球網域名稱註冊 | 網址申請, SSL憑證, 輕鬆架站, 主機空間</title>
    
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>    
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/jquery.base64.js"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/vendor/bootstrap4-datetimepicker/js/moment.min.js"></script>
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/vendor/bootstrap4-datetimepicker/js/bootstrap-datetimepicker.min.js"></script> <!---選日期--->
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/jquery.countdown.min.js"></script>
    <!-- / -->
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/global.js"></script>
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/index.js"></script>
	<!--首頁--->
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/animate.js"></script>
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/m.js?url=142302"></script>    
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/view.js"></script>
    <!------底下兩隻待拆------->
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/regex.js?url=142302"></script><!--驗證------>
    <script type="text/javascript" src="https://www.net-chinese.com.tw/nc/js/lang.js?url=142302"></script><!--語系------>
